name: configure-ami
description: Configure services and other components from the custom AMI.
schemaVersion: 1.0
phases:
  - name: build
    steps:
     - name: ConfigureAMI
       action: ExecuteBash
       inputs:
         commands:
           - |
             #!/bin/bash

             set -euo pipefail

             # Ensure '/dev/shm' is not cleaned-up (i.e., allowing us to manage it via SLURM)
             sed -r "s|^#(RemoveIPC=).+$|\1no|" -i /etc/systemd/logind.conf
  - name: test
    steps:
      - name: TestAMIConfiguration
        action: ExecuteBash
        inputs:
          commands:
            - |
              #!/bin/bash

              set -euo pipefail
              
              grep "RemoveIPC=no" /etc/systemd/logind.conf
